# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/2.0/configuration-reference/#jobs
jobs:
  build_deploy:
    resource_class: 'windows.medium'
    machine:
      image: 'windows-server-2022-gui:current'
      shell: 'cmd.exe' #'powershell.exe -ExecutionPolicy Bypass'
    steps:
      # Commands are run in a Windows virtual machine environment
      - run: git clone --recurse-submodules https://github.com/ungoogled-software/ungoogled-chromium-windows.git .
      - run:  systeminfo
      - run:
          name: "Installing Python 3.10.6"
          shell: powershell.exe
          command:  |
            Invoke-WebRequest -Uri https://www.python.org/ftp/python/3.10.6/python-3.10.6-amd64.exe -OutFile pythonInstall.exe
            Start-Process -FilePath .\pythonInstall.exe -ArgumentList "/passive /simple /quiet InstallAllUsers=1 TargetDir=C:\Python\Python310 CompileAll=1 PrependPath=1 Include_doc=0 Include_test=0" -NoNewWindow -Wait
            cmd /c rmdir /S /Q C:\tools\python\python.exe
            cmd /c mklink C:\Python\Python310\py.exe C:\Python\Python310\python.exe
            cmd /c mklink C:\Python\Python310\py3.exe C:\Python\Python310\python.exe
            cmd /c mklink C:\Python\Python310\python3.exe C:\Python\Python310\python.exe
            cmd /c mklink C:\Python\Python310\pyw.exe C:\Python\Python310\pythonw.exe
            cmd /c mklink C:\Python\Python310\py3w.exe C:\Python\Python310\pythonw.exe
      - run:
          name: "Check Python"
          shell: cmd.exe
          command: where python && python --version && echo print("Hello from Python")>pytest.py && python pytest.py && del pytest.py
      - run:
            name: "Installing 7zip"
            shell: powershell.exe
            command:  |
              Invoke-WebRequest -Uri https://www.7-zip.org/a/7z2201-x64.exe -OutFile 7zipInstall.exe
              Start-Process -FilePath .\7zipInstall.exe -ArgumentList "/S" -NoNewWindow -Wait
      - run:
            name: "Installing Visual Studio"
            shell: powershell.exe
            command:  |
              Invoke-WebRequest -Uri "https://c2rsetup.officeapps.live.com/c2r/downloadVS.aspx?sku=community&channel=Release&version=VS2022" -OutFile VSInstall.exe
              Start-Process -FilePath .\VSInstall.exe -ArgumentList "--add Microsoft.VisualStudio.Workload.NativeDesktop Microsoft.VisualStudio.Component.VC.ATLMFC --includeRecommended --quiet --passive --norestart --wait" -NoNewWindow -Wait
      - run:
            name: "Installing Windows SDK"
            shell: powershell.exe
            command: |
              Invoke-WebRequest -Uri "https://go.microsoft.com/fwlink/?linkid=2164145" -OutFile WinSDKInstall.exe
              Start-Process -FilePath .\WinSDKInstall.exe -ArgumentList "/features + /q /norestart /ceip off" -NoNewWindow -Wait
      - run: dir
      - run: py build.py
      - run: py package.py


workflows:
  version: 2
  execute_bulk:
    jobs:
      - build_deploy